openapi: 3.0.0
info:
  title: Logger Data Insertion API
  version: 1.0.0
paths:
  /v1/lora/configuration:
    post:
      summary: Insert Logger Data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoggerData'
      responses:
        '201':
          description: Logger data inserted successfully
        '400':
          description: Invalid logger data
components:
  schemas:
    LoggerData:
      type: object
      properties:
        loggerNumber:
          type: string
          maxLength: 16
          pattern: ^[0-9A-Fa-f]{1,16}$
        loggerType:
          type: string
          enum:
            - MR_810T
            - MR_821P
        baseInterval:
          type: integer
          format: int32
          default: 600
