name: Run Tests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URI: ${{ secrets.BASE_URI }}
      API_KEY: ${{ secrets.API_KEY }}
      username: ${{  secrets.username  }}
      password: ${{  secrets.password  }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'maven'
          java-version: '3.8'

      - name: Run Tests
        run: |
          mvn test
        env:
          BASE_URI: ${{ env.BASE_URI }}
          API_KEY: ${{ env.API_KEY }}
          username: ${{  env.username  }}
          password: ${{  env.password  }}
