name: Run Tests

on:
  schedule:
    - cron: '0 1 * * *'  # Schedule to run every night at 1 am CET

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Maven
        run: |
          sudo apt-get install -y maven
          mvn -v

      - name: Set up Environment Variables
        run: |
          echo "keycloak_baseUri=${{ secrets.KEYCLOAK_BASE_URI }}" >> .env
          echo "keycloak_username=${{ secrets.KEYCLOAK_USERNAME }}" >> .env
          echo "keycloak_password=${{ secrets.KEYCLOAK_PASSWORD }}" >> .env
          echo "api_baseUri=${{ secrets.API_BASE_URI }}" >> .env
          echo "api_key=${{ secrets.API_KEY }}" >> .env

      - name: Set up Configuration Properties
        run: |
          echo "keycloak.baseUri=${{ secrets.KEYCLOAK_BASE_URI }}" >> src/test/resources/config.properties
          echo "keycloak.username=${{ secrets.KEYCLOAK_USERNAME }}" >> src/test/resources/config.properties
          echo "keycloak.password=${{ secrets.KEYCLOAK_PASSWORD }}" >> src/test/resources/config.properties
          echo "api.baseUri=${{ secrets.API_BASE_URI }}" >> src/test/resources/config.properties
          echo "api.key=${{ secrets.API_KEY }}" >> src/test/resources/config.properties

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Cucumber Tests
        run: mvn test
